In [31]:
# match-level dataframe
import pandas as pd
import numpy as np

MASTER_CSV = r"C:\Users\A_R COMPUTERS\Desktop\Vineet\Project\IPL Prediction\ipl_master.csv"
master = pd.read_csv(MASTER_CSV)

# One row per match
matches = master.drop_duplicates("match_id").copy()
matches = matches.sort_values("match_date").reset_index(drop=True)

print(matches.shape)

(1175, 37)

In [32]:
# Did toss winner win the match?
matches["toss_winner_won"] = (matches["toss_winner"] == matches["winner"]).astype(int)

print(matches["toss_winner_won"].value_counts())

toss_winner_won
1    598
0    577
Name: count, dtype: int64

In [33]:
matches["toss_decision_encoded"] = matches["toss_decision"].map({"bat": 0, "field": 1})

print(matches["toss_decision_encoded"].value_counts())

toss_decision_encoded
1    770
0    405
Name: count, dtype: int64

In [34]:
matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,match_date,winner,win_by_runs,win_by_wickets,result,player_of_match,team1,team2,toss_winner_won,toss_decision_encoded
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,2008/04/18,Kolkata Knight Riders,140.0,NaN,normal,BB McCullum,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1
1,335983,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",1,0.1,Chennai Super Kings,Kings XI Punjab,PA Patel,ML Hayden,...,2008/04/19,Chennai Super Kings,33.0,NaN,normal,MEK Hussey,Punjab Kings,Chennai Super Kings,1,0
2,335984,2007/08,2008-04-19,Feroz Shah Kotla,1,0.1,Rajasthan Royals,Delhi Daredevils,T Kohli,YK Pathan,...,2008/04/19,Delhi Capitals,NaN,9.0,normal,MF Maharoof,Delhi Capitals,Rajasthan Royals,0,0
3,335986,2007/08,2008-04-20,Eden Gardens,1,0.1,Deccan Chargers,Kolkata Knight Riders,AC Gilchrist,Y Venugopal Rao,...,2008/04/20,Kolkata Knight Riders,NaN,5.0,normal,DJ Hussey,Kolkata Knight Riders,Sunrisers Hyderabad,0,0
4,335985,2007/08,2008-04-20,Wankhede Stadium,1,0.1,Mumbai Indians,Royal Challengers Bangalore,L Ronchi,ST Jayasuriya,...,2008/04/20,Royal Challengers Bengaluru,NaN,5.0,normal,MV Boucher,Mumbai Indians,Royal Challengers Bengaluru,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,1527675,2026,2026-03-29,"Wankhede Stadium, Mumbai",1,0.1,Kolkata Knight Riders,Mumbai Indians,AM Rahane,FH Allen,...,2026/03/29,Mumbai Indians,NaN,6.0,normal,SN Thakur,Kolkata Knight Riders,Mumbai Indians,1,1
1171,1527676,2026,2026-03-30,"Barsapara Cricket Stadium, Guwahati",1,0.1,Chennai Super Kings,Rajasthan Royals,SV Samson,RD Gaikwad,...,2026/03/30,Rajasthan Royals,NaN,8.0,normal,N Burger,Chennai Super Kings,Rajasthan Royals,1,1
1172,1527677,2026,2026-03-31,Maharaja Yadavindra Singh International Cricke...,1,0.1,Gujarat Titans,Punjab Kings,B Sai Sudharsan,Shubman Gill,...,2026/03/31,Punjab Kings,NaN,3.0,normal,C Connolly,Gujarat Titans,Punjab Kings,1,1
1173,1527678,2026,2026-04-01,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1,0.1,Lucknow Super Giants,Delhi Capitals,MR Marsh,RR Pant,...,2026/04/01,Delhi Capitals,NaN,6.0,normal,Sameer Rizvi,Lucknow Super Giants,Delhi Capitals,1,1
1174,1527679,2026,2026-04-02,"Eden Gardens, Kolkata",1,0.1,Sunrisers Hyderabad,Kolkata Knight Riders,TM Head,Abhishek Sharma,...,2026/04/02,Sunrisers Hyderabad,65.0,NaN,normal,Nithish Kumar Reddy,Sunrisers Hyderabad,Kolkata Knight Riders,0,1

In [35]:
# Total wins per team (all time)
total_wins = matches.groupby("winner")["match_id"].count().reset_index()
total_wins.columns = ["team", "total_wins"]

print(total_wins.sort_values("total_wins", ascending=False))

                           team  total_wins
6                Mumbai Indians         152
0           Chennai Super Kings         142
4         Kolkata Knight Riders         135
9   Royal Challengers Bengaluru         133
10          Sunrisers Hyderabad         123
7                  Punjab Kings         120
2                Delhi Capitals         119
8              Rajasthan Royals         115
1                       Defunct          46
3                Gujarat Titans          37
5          Lucknow Super Giants          30

In [36]:
matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,match_date,winner,win_by_runs,win_by_wickets,result,player_of_match,team1,team2,toss_winner_won,toss_decision_encoded
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,2008/04/18,Kolkata Knight Riders,140.0,NaN,normal,BB McCullum,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1
1,335983,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",1,0.1,Chennai Super Kings,Kings XI Punjab,PA Patel,ML Hayden,...,2008/04/19,Chennai Super Kings,33.0,NaN,normal,MEK Hussey,Punjab Kings,Chennai Super Kings,1,0
2,335984,2007/08,2008-04-19,Feroz Shah Kotla,1,0.1,Rajasthan Royals,Delhi Daredevils,T Kohli,YK Pathan,...,2008/04/19,Delhi Capitals,NaN,9.0,normal,MF Maharoof,Delhi Capitals,Rajasthan Royals,0,0
3,335986,2007/08,2008-04-20,Eden Gardens,1,0.1,Deccan Chargers,Kolkata Knight Riders,AC Gilchrist,Y Venugopal Rao,...,2008/04/20,Kolkata Knight Riders,NaN,5.0,normal,DJ Hussey,Kolkata Knight Riders,Sunrisers Hyderabad,0,0
4,335985,2007/08,2008-04-20,Wankhede Stadium,1,0.1,Mumbai Indians,Royal Challengers Bangalore,L Ronchi,ST Jayasuriya,...,2008/04/20,Royal Challengers Bengaluru,NaN,5.0,normal,MV Boucher,Mumbai Indians,Royal Challengers Bengaluru,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,1527675,2026,2026-03-29,"Wankhede Stadium, Mumbai",1,0.1,Kolkata Knight Riders,Mumbai Indians,AM Rahane,FH Allen,...,2026/03/29,Mumbai Indians,NaN,6.0,normal,SN Thakur,Kolkata Knight Riders,Mumbai Indians,1,1
1171,1527676,2026,2026-03-30,"Barsapara Cricket Stadium, Guwahati",1,0.1,Chennai Super Kings,Rajasthan Royals,SV Samson,RD Gaikwad,...,2026/03/30,Rajasthan Royals,NaN,8.0,normal,N Burger,Chennai Super Kings,Rajasthan Royals,1,1
1172,1527677,2026,2026-03-31,Maharaja Yadavindra Singh International Cricke...,1,0.1,Gujarat Titans,Punjab Kings,B Sai Sudharsan,Shubman Gill,...,2026/03/31,Punjab Kings,NaN,3.0,normal,C Connolly,Gujarat Titans,Punjab Kings,1,1
1173,1527678,2026,2026-04-01,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1,0.1,Lucknow Super Giants,Delhi Capitals,MR Marsh,RR Pant,...,2026/04/01,Delhi Capitals,NaN,6.0,normal,Sameer Rizvi,Lucknow Super Giants,Delhi Capitals,1,1
1174,1527679,2026,2026-04-02,"Eden Gardens, Kolkata",1,0.1,Sunrisers Hyderabad,Kolkata Knight Riders,TM Head,Abhishek Sharma,...,2026/04/02,Sunrisers Hyderabad,65.0,NaN,normal,Nithish Kumar Reddy,Sunrisers Hyderabad,Kolkata Knight Riders,0,1

In [37]:
#  Total matches played per team
team1_count = matches.groupby("team1")["match_id"].count().reset_index()
team1_count.columns = ["team", "matches_as_team1"]

team2_count = matches.groupby("team2")["match_id"].count().reset_index()
team2_count.columns = ["team", "matches_as_team2"]

total_matches = team1_count.merge(team2_count, on="team")
total_matches["total_matches"] = total_matches["matches_as_team1"] + total_matches["matches_as_team2"]

print(total_matches[["team", "total_matches"]].sort_values("total_matches", ascending=False))

                           team  total_matches
6                Mumbai Indians            278
10          Sunrisers Hyderabad            273
9   Royal Challengers Bengaluru            271
2                Delhi Capitals            268
4         Kolkata Knight Riders            266
7                  Punjab Kings            265
0           Chennai Super Kings            253
8              Rajasthan Royals            236
1                       Defunct            120
3                Gujarat Titans             61
5          Lucknow Super Giants             59

In [38]:
matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,match_date,winner,win_by_runs,win_by_wickets,result,player_of_match,team1,team2,toss_winner_won,toss_decision_encoded
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,2008/04/18,Kolkata Knight Riders,140.0,NaN,normal,BB McCullum,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1
1,335983,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",1,0.1,Chennai Super Kings,Kings XI Punjab,PA Patel,ML Hayden,...,2008/04/19,Chennai Super Kings,33.0,NaN,normal,MEK Hussey,Punjab Kings,Chennai Super Kings,1,0
2,335984,2007/08,2008-04-19,Feroz Shah Kotla,1,0.1,Rajasthan Royals,Delhi Daredevils,T Kohli,YK Pathan,...,2008/04/19,Delhi Capitals,NaN,9.0,normal,MF Maharoof,Delhi Capitals,Rajasthan Royals,0,0
3,335986,2007/08,2008-04-20,Eden Gardens,1,0.1,Deccan Chargers,Kolkata Knight Riders,AC Gilchrist,Y Venugopal Rao,...,2008/04/20,Kolkata Knight Riders,NaN,5.0,normal,DJ Hussey,Kolkata Knight Riders,Sunrisers Hyderabad,0,0
4,335985,2007/08,2008-04-20,Wankhede Stadium,1,0.1,Mumbai Indians,Royal Challengers Bangalore,L Ronchi,ST Jayasuriya,...,2008/04/20,Royal Challengers Bengaluru,NaN,5.0,normal,MV Boucher,Mumbai Indians,Royal Challengers Bengaluru,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,1527675,2026,2026-03-29,"Wankhede Stadium, Mumbai",1,0.1,Kolkata Knight Riders,Mumbai Indians,AM Rahane,FH Allen,...,2026/03/29,Mumbai Indians,NaN,6.0,normal,SN Thakur,Kolkata Knight Riders,Mumbai Indians,1,1
1171,1527676,2026,2026-03-30,"Barsapara Cricket Stadium, Guwahati",1,0.1,Chennai Super Kings,Rajasthan Royals,SV Samson,RD Gaikwad,...,2026/03/30,Rajasthan Royals,NaN,8.0,normal,N Burger,Chennai Super Kings,Rajasthan Royals,1,1
1172,1527677,2026,2026-03-31,Maharaja Yadavindra Singh International Cricke...,1,0.1,Gujarat Titans,Punjab Kings,B Sai Sudharsan,Shubman Gill,...,2026/03/31,Punjab Kings,NaN,3.0,normal,C Connolly,Gujarat Titans,Punjab Kings,1,1
1173,1527678,2026,2026-04-01,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1,0.1,Lucknow Super Giants,Delhi Capitals,MR Marsh,RR Pant,...,2026/04/01,Delhi Capitals,NaN,6.0,normal,Sameer Rizvi,Lucknow Super Giants,Delhi Capitals,1,1
1174,1527679,2026,2026-04-02,"Eden Gardens, Kolkata",1,0.1,Sunrisers Hyderabad,Kolkata Knight Riders,TM Head,Abhishek Sharma,...,2026/04/02,Sunrisers Hyderabad,65.0,NaN,normal,Nithish Kumar Reddy,Sunrisers Hyderabad,Kolkata Knight Riders,0,1

In [39]:
# Overall win rate per team
team_stats = total_matches.merge(total_wins, on="team")
team_stats["win_rate"] = round(team_stats["total_wins"] / team_stats["total_matches"], 2)

print(team_stats[["team", "total_matches", "total_wins", "win_rate"]].sort_values("win_rate", ascending=False))

                           team  total_matches  total_wins  win_rate
3                Gujarat Titans             61          37      0.61
0           Chennai Super Kings            253         142      0.56
6                Mumbai Indians            278         152      0.55
4         Kolkata Knight Riders            266         135      0.51
5          Lucknow Super Giants             59          30      0.51
8              Rajasthan Royals            236         115      0.49
9   Royal Challengers Bengaluru            271         133      0.49
7                  Punjab Kings            265         120      0.45
10          Sunrisers Hyderabad            273         123      0.45
2                Delhi Capitals            268         119      0.44
1                       Defunct            120          46      0.38

In [40]:
# Attach win rate to each match for team1 and team2
matches = matches.merge(team_stats[["team", "win_rate"]], left_on="team1", right_on="team", how="left")
matches = matches.rename(columns={"win_rate": "team1_win_rate"}).drop(columns="team")

matches = matches.merge(team_stats[["team", "win_rate"]], left_on="team2", right_on="team", how="left")
matches = matches.rename(columns={"win_rate": "team2_win_rate"}).drop(columns="team")

matches["win_rate_diff"] = matches["team1_win_rate"] - matches["team2_win_rate"]

print(matches[["team1", "team2", "team1_win_rate", "team2_win_rate", "win_rate_diff"]].head(10))

                         team1                        team2  team1_win_rate  \
0  Royal Challengers Bengaluru        Kolkata Knight Riders            0.49
1                 Punjab Kings          Chennai Super Kings            0.45
2               Delhi Capitals             Rajasthan Royals            0.44
3        Kolkata Knight Riders          Sunrisers Hyderabad            0.51
4               Mumbai Indians  Royal Challengers Bengaluru            0.55
5             Rajasthan Royals                 Punjab Kings            0.49
6          Sunrisers Hyderabad               Delhi Capitals            0.45
7          Chennai Super Kings               Mumbai Indians            0.56
8          Sunrisers Hyderabad             Rajasthan Royals            0.45
9                 Punjab Kings               Mumbai Indians            0.45

   team2_win_rate  win_rate_diff
0            0.51          -0.02
1            0.56          -0.11
2            0.49          -0.05
3            0.45           0.06
4            0.49           0.06
5            0.45           0.04
6            0.44           0.01
7            0.55           0.01
8            0.49          -0.04
9            0.55          -0.10

In [41]:
# Head to head wins
h2h = matches.groupby(["team1", "winner"])["match_id"].count().reset_index()
h2h.columns = ["team1", "winner", "h2h_wins"]

print(h2h.head(10))

                 team1                       winner  h2h_wins
0  Chennai Super Kings          Chennai Super Kings        76
1  Chennai Super Kings                      Defunct         1
2  Chennai Super Kings               Delhi Capitals         6
3  Chennai Super Kings               Gujarat Titans         3
4  Chennai Super Kings        Kolkata Knight Riders         6
5  Chennai Super Kings         Lucknow Super Giants         3
6  Chennai Super Kings               Mumbai Indians        13
7  Chennai Super Kings                 Punjab Kings         8
8  Chennai Super Kings             Rajasthan Royals         8
9  Chennai Super Kings  Royal Challengers Bengaluru         2

In [42]:
h2h

                   team1                       winner  h2h_wins
0    Chennai Super Kings          Chennai Super Kings        76
1    Chennai Super Kings                      Defunct         1
2    Chennai Super Kings               Delhi Capitals         6
3    Chennai Super Kings               Gujarat Titans         3
4    Chennai Super Kings        Kolkata Knight Riders         6
..                   ...                          ...       ...
106  Sunrisers Hyderabad               Mumbai Indians        10
107  Sunrisers Hyderabad                 Punjab Kings         8
108  Sunrisers Hyderabad             Rajasthan Royals         8
109  Sunrisers Hyderabad  Royal Challengers Bengaluru         5
110  Sunrisers Hyderabad          Sunrisers Hyderabad        60

[111 rows x 3 columns]

In [43]:
# Venue win rate per team
# How many times each team won at each venue
venue_wins = matches.groupby(["venue", "winner"])["match_id"].count().reset_index()
venue_wins.columns = ["venue", "team", "venue_wins"]

# How many times each team played at each venue
venue_played_t1 = matches.groupby(["venue", "team1"])["match_id"].count().reset_index()
venue_played_t1.columns = ["venue", "team", "venue_played"]

venue_played_t2 = matches.groupby(["venue", "team2"])["match_id"].count().reset_index()
venue_played_t2.columns = ["venue", "team", "venue_played"]

venue_played = pd.concat([venue_played_t1, venue_played_t2]).groupby(["venue", "team"])["venue_played"].sum().reset_index()

# Merge and compute win rate
venue_stats = venue_played.merge(venue_wins, on=["venue", "team"], how="left")
venue_stats["venue_wins"] = venue_stats["venue_wins"].fillna(0)
venue_stats["venue_win_rate"] = round(venue_stats["venue_wins"] / venue_stats["venue_played"], 2)

print(venue_stats.sort_values("venue_win_rate", ascending=False).head(10))

                                                 venue  \
254      Maharashtra Cricket Association Stadium, Pune
58                                        Buffalo Park
193                              M.Chinnaswamy Stadium
136                                         Green Park
340  Rajiv Gandhi International Stadium, Uppal, Hyd...
118                              Eden Gardens, Kolkata
341  Rajiv Gandhi International Stadium, Uppal, Hyd...
116                              Eden Gardens, Kolkata
346  Rajiv Gandhi International Stadium, Uppal, Hyd...
228  Maharaja Yadavindra Singh International Cricke...

                            team  venue_played  venue_wins  venue_win_rate
254             Rajasthan Royals             2         2.0             1.0
58           Chennai Super Kings             1         1.0             1.0
193        Kolkata Knight Riders             2         2.0             1.0
136               Delhi Capitals             1         1.0             1.0
340               Gujarat Titans             1         1.0             1.0
118               Gujarat Titans             3         3.0             1.0
341        Kolkata Knight Riders             1         1.0             1.0
116          Chennai Super Kings             2         2.0             1.0
346  Royal Challengers Bengaluru             2         2.0             1.0
228               Gujarat Titans             1         1.0             1.0

In [44]:
# Target variable 
matches["target"] = (matches["winner"] == matches["team1"]).astype(int)

print("Target distribution:")
print(matches["target"].value_counts())
print("Team1 win %:", round(matches["target"].mean() * 100, 2), "%")

Target distribution:
target
0    592
1    583
Name: count, dtype: int64
Team1 win %: 49.62 %

In [45]:
matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,player_of_match,team1,team2,toss_winner_won,toss_decision_encoded,team1_win_rate,team2_win_rate,win_rate_diff,target
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,normal,BB McCullum,Royal Challengers Bengaluru,Kolkata Knight Riders,0,1,0.49,0.51,-0.02,0
1,335983,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",1,0.1,Chennai Super Kings,Kings XI Punjab,PA Patel,ML Hayden,...,normal,MEK Hussey,Punjab Kings,Chennai Super Kings,1,0,0.45,0.56,-0.11,0
2,335984,2007/08,2008-04-19,Feroz Shah Kotla,1,0.1,Rajasthan Royals,Delhi Daredevils,T Kohli,YK Pathan,...,normal,MF Maharoof,Delhi Capitals,Rajasthan Royals,0,0,0.44,0.49,-0.05,1
3,335986,2007/08,2008-04-20,Eden Gardens,1,0.1,Deccan Chargers,Kolkata Knight Riders,AC Gilchrist,Y Venugopal Rao,...,normal,DJ Hussey,Kolkata Knight Riders,Sunrisers Hyderabad,0,0,0.51,0.45,0.06,1
4,335985,2007/08,2008-04-20,Wankhede Stadium,1,0.1,Mumbai Indians,Royal Challengers Bangalore,L Ronchi,ST Jayasuriya,...,normal,MV Boucher,Mumbai Indians,Royal Challengers Bengaluru,0,0,0.55,0.49,0.06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,1527675,2026,2026-03-29,"Wankhede Stadium, Mumbai",1,0.1,Kolkata Knight Riders,Mumbai Indians,AM Rahane,FH Allen,...,normal,SN Thakur,Kolkata Knight Riders,Mumbai Indians,1,1,0.51,0.55,-0.04,0
1171,1527676,2026,2026-03-30,"Barsapara Cricket Stadium, Guwahati",1,0.1,Chennai Super Kings,Rajasthan Royals,SV Samson,RD Gaikwad,...,normal,N Burger,Chennai Super Kings,Rajasthan Royals,1,1,0.56,0.49,0.07,0
1172,1527677,2026,2026-03-31,Maharaja Yadavindra Singh International Cricke...,1,0.1,Gujarat Titans,Punjab Kings,B Sai Sudharsan,Shubman Gill,...,normal,C Connolly,Gujarat Titans,Punjab Kings,1,1,0.61,0.45,0.16,0
1173,1527678,2026,2026-04-01,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1,0.1,Lucknow Super Giants,Delhi Capitals,MR Marsh,RR Pant,...,normal,Sameer Rizvi,Lucknow Super Giants,Delhi Capitals,1,1,0.51,0.44,0.07,0
1174,1527679,2026,2026-04-02,"Eden Gardens, Kolkata",1,0.1,Sunrisers Hyderabad,Kolkata Knight Riders,TM Head,Abhishek Sharma,...,normal,Nithish Kumar Reddy,Sunrisers Hyderabad,Kolkata Knight Riders,0,1,0.45,0.51,-0.06,1

In [46]:
FEATURES_CSV = r"C:\Users\A_R COMPUTERS\Desktop\Vineet\Project\IPL Prediction\ipl_features.csv"
matches.to_csv(FEATURES_CSV, index=False)

print("Saved! Shape:", matches.shape)
print("Columns:", matches.columns.tolist())

Saved! Shape: (1175, 43)
Columns: ['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed', 'city', 'gender', 'match_type', 'toss_winner', 'toss_decision', 'event', 'match_number', 'match_date', 'winner', 'win_by_runs', 'win_by_wickets', 'result', 'player_of_match', 'team1', 'team2', 'toss_winner_won', 'toss_decision_encoded', 'team1_win_rate', 'team2_win_rate', 'win_rate_diff', 'target']

In [47]:
print("Final feature dataframe shape:", matches.shape)
print("\nAll columns:")
for col in matches.columns.tolist():
    print(" -", col)

Final feature dataframe shape: (1175, 43)

All columns:
 - match_id
 - season
 - start_date
 - venue
 - innings
 - ball
 - batting_team
 - bowling_team
 - striker
 - non_striker
 - bowler
 - runs_off_bat
 - extras
 - wides
 - noballs
 - byes
 - legbyes
 - penalty
 - wicket_type
 - player_dismissed
 - other_wicket_type
 - other_player_dismissed
 - city
 - gender
 - match_type
 - toss_winner
 - toss_decision
 - event
 - match_number
 - match_date
 - winner
 - win_by_runs
 - win_by_wickets
 - result
 - player_of_match
 - team1
 - team2
 - toss_winner_won
 - toss_decision_encoded
 - team1_win_rate
 - team2_win_rate
 - win_rate_diff
 - target

In [48]:
# Keep only match-level meaningful columns
match_cols = [
    "match_id", "season", "match_date",
    "team1", "team2", "venue", "city",
    "toss_winner", "toss_decision",
    "toss_winner_won", "toss_decision_encoded",
    "team1_win_rate", "team2_win_rate", "win_rate_diff",
    "winner", "result", "target"
]

matches_clean = matches[match_cols].copy()

print("Clean shape:", matches_clean.shape)
print("Columns:", matches_clean.columns.tolist())
print("\nSample:")
print(matches_clean.head(5).to_string())

Clean shape: (1175, 17)
Columns: ['match_id', 'season', 'match_date', 'team1', 'team2', 'venue', 'city', 'toss_winner', 'toss_decision', 'toss_winner_won', 'toss_decision_encoded', 'team1_win_rate', 'team2_win_rate', 'win_rate_diff', 'winner', 'result', 'target']

Sample:
   match_id   season  match_date                        team1                        team2                                       venue        city                  toss_winner toss_decision  toss_winner_won  toss_decision_encoded  team1_win_rate  team2_win_rate  win_rate_diff                       winner  result  target
0    335982  2007/08  2008/04/18  Royal Challengers Bengaluru        Kolkata Knight Riders                       M Chinnaswamy Stadium   Bangalore  Royal Challengers Bengaluru         field                0                      1            0.49            0.51          -0.02        Kolkata Knight Riders  normal       0
1    335983  2007/08  2008/04/19                 Punjab Kings          Chennai Super Kings  Punjab Cricket Association Stadium, Mohali  Chandigarh          Chennai Super Kings           bat                1                      0            0.45            0.56          -0.11          Chennai Super Kings  normal       0
2    335984  2007/08  2008/04/19               Delhi Capitals             Rajasthan Royals                            Feroz Shah Kotla       Delhi             Rajasthan Royals           bat                0                      0            0.44            0.49          -0.05               Delhi Capitals  normal       1
3    335986  2007/08  2008/04/20        Kolkata Knight Riders          Sunrisers Hyderabad                                Eden Gardens     Kolkata          Sunrisers Hyderabad           bat                0                      0            0.51            0.45           0.06        Kolkata Knight Riders  normal       1
4    335985  2007/08  2008/04/20               Mumbai Indians  Royal Challengers Bengaluru                            Wankhede Stadium      Mumbai               Mumbai Indians           bat                0                      0            0.55            0.49           0.06  Royal Challengers Bengaluru  normal       0

In [49]:
FEATURES_CSV = r"C:\Users\A_R COMPUTERS\Desktop\Vineet\Project\IPL Prediction\ipl_features.csv"
matches_clean.to_csv(FEATURES_CSV, index=False)

print("Saved! Shape:", matches_clean.shape)

Saved! Shape: (1175, 17)